### ISSUE TITLE
POTENTIAL BUG: We can not send SIGINT to main `vsh` process

### ISSUE THREAD

**Issue by jbrinksma** [OscarMulder/codam-42sh#315]
Because we never actually respond to the SIGINT signal, (we always ignore it completely, and just respond to a '\4' character when CTRL+C is pressed

**Comment by robkuijper** [comment]
This is actually expected behaviour, since we don't want the main shell to be able to die of a SIGINT signal. Any invocation of a SIGINT targeting a subgroup of the shell will also call it on the parent (vsh). We do not want the shell to die in this case, so we just ignore any and all explicit SIGINT signals called on vsh.
